### PR TITLE
update fonts to be woff

### PR DESCRIPTION
**Pull request by peter-mouland**
I removed `ttf` and moved fonts into a separate css file. This reduces the file size from `>500kb` to `~150kb`

For greater browser support I manually converted `woff2` to `woff`, so if anyone has an original woff file, that would be appreciated.

### CODE REVIEW

**Comment by andrewmerrell** [comment]
Fonts located at:

web.static.nowtv.com/fonts/nowtvtext-light.woff
web.static.nowtv.com/fonts/nowtvtext-regular.woff
web.static.nowtv.com/fonts/nowtvtext-bold.woff

Should allow us to make sure we meet the regulation of blocking downloads if not from nowtv.com (or bskyb.com/sky.com domain) part of our font license agreement.

Need to check if we're allowed to inline the font in css.

**Comment by peter-mouland** [comment]
great, updated to use those fonts.
Pointing to a CDN version of fonts will be a new PR

**Comment by bentidy** [comment]
:-1: Removed the seahorse

**Comment by nowarkdev** [comment]
@ariley90 What was the thinking behind the changes to the webpack config? We were producing a seperate style-guide.css file but now it seems to be included within the toolkit.css? Is this not unnecessary for our apps to consume?

**Comment by peter-mouland** [comment]
if that's happening - it was unintentional! i'll double check...

**Comment by peter-mouland** [comment]
@ariley90 Fixed

**Comment by nowarkdev** [comment]
@roryp2 :thumbsup:

**Pull request merged**
